server:
  port: 8088

spring:
  application:
    name: mybatis-demo

  datasource:
    url: jdbc:mysql://localhost:3306/test-mybatis
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
